// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9U86sy_jVVJh0KV0U8F741cGCkMgje1E',
    appId: '1:938513249908:web:6a177c2d86ebcb2f114321',
    messagingSenderId: '938513249908',
    projectId: 'flutter-notifikasi-prakt-7ad63',
    authDomain: 'flutter-notifikasi-prakt-7ad63.firebaseapp.com',
    storageBucket: 'flutter-notifikasi-prakt-7ad63.firebasestorage.app',
    measurementId: 'G-496ZH4SVZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS33OMQVF8noo1yMy89FGJkEfBXrYtkXc',
    appId: '1:938513249908:android:4e9867b14e8f854b114321',
    messagingSenderId: '938513249908',
    projectId: 'flutter-notifikasi-prakt-7ad63',
    storageBucket: 'flutter-notifikasi-prakt-7ad63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGCKUdxO-7ayK01pz7YiVuO8VyDhFmHDI',
    appId: '1:938513249908:ios:2472298745bce805114321',
    messagingSenderId: '938513249908',
    projectId: 'flutter-notifikasi-prakt-7ad63',
    storageBucket: 'flutter-notifikasi-prakt-7ad63.firebasestorage.app',
    iosClientId: '938513249908-efc319s139173kobab8i76m2t0ip3h42.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgifyAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGCKUdxO-7ayK01pz7YiVuO8VyDhFmHDI',
    appId: '1:938513249908:ios:2472298745bce805114321',
    messagingSenderId: '938513249908',
    projectId: 'flutter-notifikasi-prakt-7ad63',
    storageBucket: 'flutter-notifikasi-prakt-7ad63.firebasestorage.app',
    iosClientId: '938513249908-efc319s139173kobab8i76m2t0ip3h42.apps.googleusercontent.com',
    iosBundleId: 'com.example.budgifyAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9U86sy_jVVJh0KV0U8F741cGCkMgje1E',
    appId: '1:938513249908:web:51cc65475928d553114321',
    messagingSenderId: '938513249908',
    projectId: 'flutter-notifikasi-prakt-7ad63',
    authDomain: 'flutter-notifikasi-prakt-7ad63.firebaseapp.com',
    storageBucket: 'flutter-notifikasi-prakt-7ad63.firebasestorage.app',
    measurementId: 'G-Z5KX70ZE21',
  );
}
